version: '3.8'
services:
    db:
        image: postgres:15.1-bullseye
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'
        volumes:
            - ./db-init.sql:/docker-entrypoint-initdb.d/create_database.sql
        container_name: postgres_db
volumes:
    db:
        driver: local
